from .auth import (
    accept_friend_request,
    cancel_friend_request,
    decline_friend_request,
    delete_account,
    friends_list,
    login_user,
    logout_user,
    profile_user,
    register,
    remove_friend,
    send_friend_request,
)
from .clubs import club_detail, club_new, clubs, confirm_club_switch, join_club, leave_club
from .events import widok_eventow
from .home import about, cars, community, index, recommendations, submit_room_vote, voting_room_detail, voting_room_new, voting_rooms

__all__ = [
    "about",
    "accept_friend_request",
    "cancel_friend_request",
    "cars",
    "club_detail",
    "club_new",
    "clubs",
    "community",
    "confirm_club_switch",
    "decline_friend_request",
    "delete_account",
    "friends_list",
    "index",
    "join_club",
    "leave_club",
    "login_user",
    "logout_user",
    "profile_user",
    "recommendations",
    "register",
    "remove_friend",
    "send_friend_request",
    "submit_room_vote",
    "voting_room_detail",
    "voting_room_new",
    "voting_rooms",
    "widok_eventow",
]