# Generated by Django 6.0.3 on 2026-04-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_club_profile_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='icon',
            field=models.CharField(default='', max_length=50),
        ),
    ]
