# Generated by Django 6.0.3 on 2026-03-27 16:51

from django.db import migrations, models


def set_catalog_defaults(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    presets = {
        "film": {
            "vibe": "spokojny",
            "duration_minutes": 120,
            "cost_level": "cheap",
            "group_size": "duo",
            "weather_fit": "rain",
            "setting": "home",
            "pick_reason": "Dobry wybor, gdy chcecie gotowy plan bez duzego przygotowania.",
        },
        "serial": {
            "vibe": "w_domu",
            "duration_minutes": 60,
            "cost_level": "cheap",
            "group_size": "duo",
            "weather_fit": "rain",
            "setting": "home",
            "pick_reason": "Sprawdza sie, kiedy chcecie po prostu usiasc i odpalic cos lekkiego.",
        },
        "gra": {
            "vibe": "ekipa",
            "duration_minutes": 90,
            "cost_level": "medium",
            "group_size": "group",
            "weather_fit": "rain",
            "setting": "home",
            "pick_reason": "Dobre, gdy chcecie ruszyc wieczor i wlaczyc wszystkich do zabawy.",
        },
        "aktywnosci": {
            "vibe": "na_miescie",
            "duration_minutes": 150,
            "cost_level": "medium",
            "group_size": "group",
            "weather_fit": "sun",
            "setting": "outside",
            "pick_reason": "Dobry wybor, kiedy macie ochote wyjsc z domu i zrobic cos razem.",
        },
    }

    fields = [
        "vibe",
        "duration_minutes",
        "cost_level",
        "group_size",
        "weather_fit",
        "setting",
        "pick_reason",
    ]

    for post in Post.objects.all():
        preset = presets.get(post.category, presets["film"])
        for field_name, value in preset.items():
            setattr(post, field_name, value)
        post.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_favoritepost"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cost_level",
            field=models.CharField(
                choices=[("free", "Za darmo"), ("cheap", "Tanie"), ("medium", "Średni budżet")],
                default="cheap",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=90, verbose_name="Czas trwania (min)"),
        ),
        migrations.AddField(
            model_name="post",
            name="group_size",
            field=models.CharField(
                choices=[("solo", "Solo"), ("duo", "2 osoby"), ("group", "Grupa")],
                default="group",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="pick_reason",
            field=models.CharField(
                default="Dobry wybór, gdy nie chce wam się długo planować.",
                max_length=140,
                verbose_name="Powód wyboru",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="setting",
            field=models.CharField(
                choices=[("home", "W domu"), ("outside", "Na mieście"), ("flex", "Dowolnie")],
                default="home",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="vibe",
            field=models.CharField(
                choices=[
                    ("spokojny", "Na spokojny wieczór"),
                    ("ekipa", "Z ekipą"),
                    ("romantycznie", "Romantycznie"),
                    ("budzetowo", "Budżetowo"),
                    ("w_domu", "W domu"),
                    ("na_miescie", "Na mieście"),
                ],
                default="spokojny",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="weather_fit",
            field=models.CharField(
                choices=[("rain", "Na deszcz"), ("sun", "Na słoneczny dzień"), ("any", "Na każdą pogodę")],
                default="any",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_catalog_defaults, migrations.RunPython.noop),
    ]
