# Generated by Django 6.0.3 on 2026-03-27 17:49

from django.db import migrations, models


def seed_catalog_tags(apps, schema_editor):
    CatalogTag = apps.get_model("posts", "CatalogTag")
    Post = apps.get_model("posts", "Post")

    tag_specs = [
        ("Na spokojny wieczór", "na-spokojny-wieczor", 1),
        ("Z ekipą", "z-ekipa", 2),
        ("Romantycznie", "romantycznie", 3),
        ("Budżetowo", "budzetowo", 4),
        ("W domu", "w-domu", 5),
        ("Na mieście", "na-miescie", 6),
        ("Na deszcz", "na-deszcz", 7),
        ("Na słońce", "na-slonce", 8),
        ("Dla dwojga", "dla-dwojga", 9),
        ("Solo", "solo", 10),
    ]
    tags = {}
    for name, slug, sort_order in tag_specs:
        tags[slug], _ = CatalogTag.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "sort_order": sort_order},
        )

    vibe_map = {
        "spokojny": "na-spokojny-wieczor",
        "ekipa": "z-ekipa",
        "romantycznie": "romantycznie",
        "budzetowo": "budzetowo",
        "w_domu": "w-domu",
        "na_miescie": "na-miescie",
    }
    setting_map = {
        "home": "w-domu",
        "outside": "na-miescie",
    }
    weather_map = {
        "rain": "na-deszcz",
        "sun": "na-slonce",
    }
    group_map = {
        "solo": "solo",
        "duo": "dla-dwojga",
        "group": "z-ekipa",
    }

    for post in Post.objects.all():
        post_tags = set()

        if post.vibe in vibe_map:
            post_tags.add(vibe_map[post.vibe])
        if post.setting in setting_map:
            post_tags.add(setting_map[post.setting])
        if post.weather_fit in weather_map:
            post_tags.add(weather_map[post.weather_fit])
        if post.group_size in group_map:
            post_tags.add(group_map[post.group_size])
        if post.cost_level in {"free", "cheap"}:
            post_tags.add("budzetowo")

        for slug in post_tags:
            post.tags.add(tags[slug])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_cost_level_post_duration_minutes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=40, unique=True)),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="posts", to="posts.catalogtag"),
        ),
        migrations.RunPython(seed_catalog_tags, migrations.RunPython.noop),
    ]
