# Generated by Django 6.0.3 on 2026-04-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_alter_post_author_alter_post_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cena",
            field=models.CharField(
                blank=True,
                choices=[
                    ("za_darmo", "Za darmo"),
                    ("tanio", "Tanio"),
                    ("srednio", "\u015arednio"),
                    ("drogo", "Drogo"),
                ],
                default="",
                max_length=30,
                verbose_name="Cena",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="liczba_osob",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1_osoba", "1 osoba"),
                    ("2_osoby", "2 osoby"),
                    ("grupa", "Grupa (3+)"),
                ],
                default="",
                max_length=30,
                verbose_name="Liczba os\u00f3b",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="okazja",
            field=models.CharField(
                blank=True,
                choices=[
                    ("na_randke", "Na randk\u0119"),
                    ("ze_znajomymi", "Ze znajomymi"),
                    ("solo", "Samemu (Solo)"),
                ],
                default="",
                max_length=30,
                verbose_name="Okazja",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tagi",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Filmy/Seriale",
                        [
                            ("akcja", "Akcja"),
                            ("komedia", "Komedia"),
                            ("dramat", "Dramat"),
                            ("horror", "Horror"),
                            ("sci_fi", "Sci-Fi"),
                            ("do_obiadu", "Do obiadu"),
                        ],
                    ),
                    (
                        "Gry",
                        [
                            ("rpg", "RPG"),
                            ("fps", "FPS"),
                            ("strategia", "Strategia"),
                            ("przygodowa", "Przygodowa"),
                            ("logiczna", "Logiczna"),
                        ],
                    ),
                    (
                        "Aktywno\u015bci",
                        [
                            ("sport", "Sport"),
                            ("jedzenie", "Jedzenie"),
                            ("spacer", "Spacer"),
                            ("impreza", "Impreza"),
                            ("kino", "Kino"),
                            ("kultura", "Kultura"),
                        ],
                    ),
                ],
                default="",
                max_length=30,
                verbose_name="Tagi",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("film", "Film"),
                    ("serial", "Serial"),
                    ("gra", "Gra"),
                    ("aktywnosci", "Aktywno\u015bci"),
                ],
                default="film",
                max_length=20,
                verbose_name="Kategoria",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=75, verbose_name="Tytu\u0142"),
        ),
    ]
