# Generated by Django 6.0.3 on 2026-04-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_post_cena_post_liczba_osob_post_okazja_post_tagi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="podtag_anime",
            field=models.CharField(
                blank=True,
                choices=[
                    ("shonen", "Shonen"),
                    ("seinen", "Seinen"),
                    ("fantasy", "Fantasy"),
                ],
                default="",
                max_length=30,
                verbose_name="Dodatkowy tag anime",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tagi",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Filmy/Seriale",
                        [
                            ("akcja", "Akcja"),
                            ("anime", "Anime"),
                            ("animacja", "Animacja"),
                            ("komedia", "Komedia"),
                            ("dramat", "Dramat"),
                            ("horror", "Horror"),
                            ("sci_fi", "Sci-Fi"),
                            ("do_obiadu", "Do obiadu"),
                        ],
                    ),
                    (
                        "Gry",
                        [
                            ("rpg", "RPG"),
                            ("fps", "FPS"),
                            ("strategia", "Strategia"),
                            ("przygodowa", "Przygodowa"),
                            ("logiczna", "Logiczna"),
                        ],
                    ),
                    (
                        "Aktywno\u015bci",
                        [
                            ("sport", "Sport"),
                            ("jedzenie", "Jedzenie"),
                            ("spacer", "Spacer"),
                            ("impreza", "Impreza"),
                            ("kino", "Kino"),
                            ("kultura", "Kultura"),
                        ],
                    ),
                ],
                default="",
                max_length=30,
                verbose_name="Tagi",
            ),
        ),
    ]
