# Generated by Django 6.0.3 on 2026-03-27 18:16

from django.db import migrations, models


def seed_film_configuration(apps, schema_editor):
    CatalogTag = apps.get_model("posts", "CatalogTag")
    Post = apps.get_model("posts", "Post")

    film_tags = [
        ("Komedia", "film-komedia", 1),
        ("Dramat", "film-dramat", 2),
        ("Thriller", "film-thriller", 3),
        ("Horror", "film-horror", 4),
        ("Sci-fi", "film-sci-fi", 5),
        ("Fantasy", "film-fantasy", 6),
        ("Akcja", "film-akcja", 7),
        ("Romans", "film-romans", 8),
        ("Kryminał", "film-kryminal", 9),
        ("Przygodowy", "film-przygodowy", 10),
        ("Psychologiczny", "film-psychologiczny", 11),
        ("Historyczny", "film-historyczny", 12),
        ("Wojenny", "film-wojenny", 13),
        ("Mroczny", "film-mroczny", 14),
        ("Lekki", "film-lekki", 15),
        ("Wzruszający", "film-wzruszajacy", 16),
        ("Epicki", "film-epicki", 17),
        ("Nostalgiczny", "film-nostalgiczny", 18),
        ("Na randkę", "film-na-randke", 19),
        ("Na spokojny wieczór", "film-na-spokojny-wieczor", 20),
        ("Do przemyśleń", "film-do-przemyslen", 21),
        ("Na wyłączenie głowy", "film-na-wylaczenie-glowy", 22),
    ]

    seeded_tags = {}
    for name, slug, sort_order in film_tags:
        seeded_tags[slug], _ = CatalogTag.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "scope": "film", "sort_order": sort_order},
        )

    CatalogTag.objects.exclude(slug__in=seeded_tags.keys()).update(scope="shared")

    for post in Post.objects.filter(category="film"):
        if not post.subcategory:
            post.subcategory = "fabularny"
            post.save(update_fields=["subcategory"])

        if post.vibe == "romantycznie":
            post.tags.add(seeded_tags["film-na-randke"])
        if post.vibe == "spokojny":
            post.tags.add(seeded_tags["film-na-spokojny-wieczor"])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_catalogtag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catalogtag",
            options={"ordering": ["scope", "sort_order", "name"]},
        ),
        migrations.AlterField(
            model_name="catalogtag",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name="catalogtag",
            name="scope",
            field=models.CharField(
                choices=[("shared", "Wspólne"), ("film", "Film")],
                default="shared",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="subcategory",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(seed_film_configuration, migrations.RunPython.noop),
    ]
