# Generated by Django 6.0.3 on 2026-03-27 19:32

from django.db import migrations, models


def seed_serial_configuration(apps, schema_editor):
    CatalogTag = apps.get_model("posts", "CatalogTag")
    Post = apps.get_model("posts", "Post")

    serial_tags = [
        ("Komedia", "serial-komedia", 1),
        ("Dramat", "serial-dramat", 2),
        ("Thriller", "serial-thriller", 3),
        ("Horror", "serial-horror", 4),
        ("Sci-fi", "serial-sci-fi", 5),
        ("Fantasy", "serial-fantasy", 6),
        ("Romans", "serial-romans", 7),
        ("Kryminał", "serial-kryminal", 8),
        ("Obyczajowy", "serial-obyczajowy", 9),
        ("Historyczny", "serial-historyczny", 10),
        ("Mystery", "serial-mystery", 11),
        ("True crime", "serial-true-crime", 12),
        ("Comfort show", "serial-comfort-show", 13),
        ("Wciągający", "serial-wciagajacy", 14),
        ("Slow burn", "serial-slow-burn", 15),
        ("Cliffhangery", "serial-cliffhangery", 16),
        ("Lekki", "serial-lekki", 17),
        ("Mroczny", "serial-mroczny", 18),
        ("Na weekend", "serial-na-weekend", 19),
        ("Do binge", "serial-do-binge", 20),
        ("Do wspólnego oglądania", "serial-do-wspolnego-ogladania", 21),
        ("Na dłuższą przygodę", "serial-na-dluzsza-przygode", 22),
        ("Krótkie odcinki", "serial-krotkie-odcinki", 23),
        ("Zamknięta historia", "serial-zamknieta-historia", 24),
    ]

    seeded_tags = {}
    for name, slug, sort_order in serial_tags:
        seeded_tags[slug], _ = CatalogTag.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "scope": "serial", "sort_order": sort_order},
        )

    for post in Post.objects.filter(category="serial"):
        if not post.subcategory:
            post.subcategory = "dramatyczny"
            post.save(update_fields=["subcategory"])

        if post.vibe == "spokojny":
            post.tags.add(seeded_tags["serial-comfort-show"])
        if post.vibe == "ekipa":
            post.tags.add(seeded_tags["serial-do-wspolnego-ogladania"])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_alter_catalogtag_options_catalogtag_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogtag",
            name="scope",
            field=models.CharField(
                choices=[("shared", "Wspólne"), ("film", "Film"), ("serial", "Serial")],
                default="shared",
                max_length=20,
            ),
        ),
        migrations.RunPython(seed_serial_configuration, migrations.RunPython.noop),
    ]
