# Generated by Django 6.0.3 on 2026-03-28 11:08

from django.db import migrations, models


def infer_game_subcategory(post):
    text = f"{post.title} {post.body}".lower()

    if "plansz" in text:
        return "planszowa"
    if "karc" in text:
        return "karciana"
    if "quiz" in text:
        return "quizowa"
    if "mobil" in text:
        return "mobilna"
    if "rpg" in text:
        return "rpg"
    if "imprez" in text or "party" in text:
        return "imprezowa"
    if "logicz" in text or "puzz" in text or "lamig" in text:
        return "logiczna"
    if "coop" in text or "co-op" in text or "kooper" in text:
        return "kooperacyjna"

    return "gra_wideo"


def seed_game_configuration(apps, schema_editor):
    CatalogTag = apps.get_model("posts", "CatalogTag")
    Post = apps.get_model("posts", "Post")

    game_tags = [
        ("Co-op", "gra-co-op", 1),
        ("Versus", "gra-versus", 2),
        ("Lokalnie", "gra-lokalnie", 3),
        ("Online", "gra-online", 4),
        ("Couch co-op", "gra-couch-co-op", 5),
        ("Strategiczna", "gra-strategiczna", 6),
        ("Casual", "gra-casual", 7),
        ("Hardcore", "gra-hardcore", 8),
        ("Relaksująca", "gra-relaksujaca", 9),
        ("Chaotyczna", "gra-chaotyczna", 10),
        ("Szybka", "gra-szybka", 11),
        ("Wymagająca", "gra-wymagajaca", 12),
        ("Śmieszna", "gra-smieszna", 13),
        ("Fabularna", "gra-fabularna", 14),
        ("Narracyjna", "gra-narracyjna", 15),
        ("Survival", "gra-survival", 16),
        ("Crafting", "gra-crafting", 17),
        ("Eksploracja", "gra-eksploracja", 18),
        ("Puzzle", "gra-puzzle", 19),
        ("Rywalizacja", "gra-rywalizacja", 20),
        ("Na śmiech", "gra-na-smiech", 21),
        ("Na cały wieczór", "gra-na-caly-wieczor", 22),
        ("Dla początkujących", "gra-dla-poczatkujacych", 23),
        ("Dla ogranych", "gra-dla-ogranych", 24),
    ]

    seeded_tags = {}
    for name, slug, sort_order in game_tags:
        seeded_tags[slug], _ = CatalogTag.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "scope": "gra", "sort_order": sort_order},
        )

    for post in Post.objects.filter(category="gra"):
        text = f"{post.title} {post.body}".lower()

        if not post.subcategory:
            post.subcategory = infer_game_subcategory(post)
            post.save(update_fields=["subcategory"])

        if "plansz" in text or "karc" in text:
            post.tags.add(seeded_tags["gra-lokalnie"])
        if "online" in text:
            post.tags.add(seeded_tags["gra-online"])
        if post.vibe == "ekipa":
            post.tags.add(seeded_tags["gra-na-smiech"])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_alter_catalogtag_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogtag",
            name="scope",
            field=models.CharField(
                choices=[("shared", "Wspólne"), ("film", "Film"), ("serial", "Serial"), ("gra", "Gra")],
                default="shared",
                max_length=20,
            ),
        ),
        migrations.RunPython(seed_game_configuration, migrations.RunPython.noop),
    ]
