# Generated by Django 6.0.3 on 2026-03-28 11:24

from django.db import migrations, models


def infer_activity_subcategory(post):
    text = f"{post.title} {post.body}".lower()

    if any(keyword in text for keyword in ["spacer", "piknik", "rower", "park", "plener", "fotospacer"]):
        return "plenerowa"
    if any(keyword in text for keyword in ["joga", "basen", "silown", "siłown", "sport", "taniec"]):
        return "sportowa"
    if any(keyword in text for keyword in ["gotow", "piec", "kolacja", "kuch"]):
        return "kulinarna"
    if any(keyword in text for keyword in ["warsztat", "malow", "rysow", "lep", "foto"]):
        return "kreatywna"
    if any(keyword in text for keyword in ["muze", "wystaw", "kino", "koncert", "teatr"]):
        return "kulturalna"
    if any(keyword in text for keyword in ["sauna", "spa", "relaks", "masaz", "masaż"]):
        return "relaksacyjna"
    if any(keyword in text for keyword in ["swiate", "święt", "bozonarod", "bożonarod", "lato", "wakac", "zima"]):
        return "sezonowa"
    if any(keyword in text for keyword in ["karaoke", "bilard", "kregl", "kręgl", "plansz", "escape room"]):
        return "towarzyska"
    if post.setting == "outside":
        return "na_miescie"
    return "domowa"


def seed_activity_configuration(apps, schema_editor):
    CatalogTag = apps.get_model("posts", "CatalogTag")
    Post = apps.get_model("posts", "Post")

    activity_tags = [
        ("Spacer", "aktywnosci-spacer", 1),
        ("Piknik", "aktywnosci-piknik", 2),
        ("Gotowanie", "aktywnosci-gotowanie", 3),
        ("Pieczenie", "aktywnosci-pieczenie", 4),
        ("Planszówki", "aktywnosci-planszowki", 5),
        ("Karaoke", "aktywnosci-karaoke", 6),
        ("Bilard", "aktywnosci-bilard", 7),
        ("Kręgle", "aktywnosci-kregle", 8),
        ("Muzeum", "aktywnosci-muzeum", 9),
        ("Wystawa", "aktywnosci-wystawa", 10),
        ("Koncert", "aktywnosci-koncert", 11),
        ("Kino", "aktywnosci-kino", 12),
        ("Escape room", "aktywnosci-escape-room", 13),
        ("Rower", "aktywnosci-rower", 14),
        ("Joga", "aktywnosci-joga", 15),
        ("Sauna", "aktywnosci-sauna", 16),
        ("Fotospacer", "aktywnosci-fotospacer", 17),
        ("Warsztaty", "aktywnosci-warsztaty", 18),
        ("Na randkę", "aktywnosci-na-randke", 19),
        ("Last minute", "aktywnosci-last-minute", 20),
        ("Bez rezerwacji", "aktywnosci-bez-rezerwacji", 21),
        ("Z rezerwacją", "aktywnosci-z-rezerwacja", 22),
        ("Spokojnie", "aktywnosci-spokojnie", 23),
        ("Aktywnie", "aktywnosci-aktywnie", 24),
    ]

    seeded_tags = {}
    for name, slug, sort_order in activity_tags:
        seeded_tags[slug], _ = CatalogTag.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "scope": "aktywnosci", "sort_order": sort_order},
        )

    for post in Post.objects.filter(category="aktywnosci"):
        text = f"{post.title} {post.body}".lower()

        if not post.subcategory:
            post.subcategory = infer_activity_subcategory(post)
            post.save(update_fields=["subcategory"])

        if "spacer" in text:
            post.tags.add(seeded_tags["aktywnosci-spacer"])
        if "kino" in text:
            post.tags.add(seeded_tags["aktywnosci-kino"])
        if "warsztat" in text:
            post.tags.add(seeded_tags["aktywnosci-warsztaty"])
        if post.vibe == "romantycznie":
            post.tags.add(seeded_tags["aktywnosci-na-randke"])
        if post.vibe == "spokojny":
            post.tags.add(seeded_tags["aktywnosci-spokojnie"])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_alter_catalogtag_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogtag",
            name="scope",
            field=models.CharField(
                choices=[
                    ("shared", "Wspólne"),
                    ("film", "Film"),
                    ("serial", "Serial"),
                    ("gra", "Gra"),
                    ("aktywnosci", "Aktywności"),
                ],
                default="shared",
                max_length=20,
            ),
        ),
        migrations.RunPython(seed_activity_configuration, migrations.RunPython.noop),
    ]
