# Generated by Django 6.0.3 on 2026-03-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_alter_catalogtag_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="season_count",
            field=models.PositiveIntegerField(default=1, verbose_name="Liczba sezonów"),
        ),
    ]
