# Generated by Django 6.0.3 on 2026-03-25 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0005_favoritepost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('body', models.TextField(verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('catalog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
